data_pre_processing:
  clip_length: 16
  resize: [112,112]
  precision: "float32"

data_loader:
  batch_size: 8   # try 2 if AMP active
  drop_last: True

optimizer:
  type: "Adam"
  lr: 0.001
  weight_decay: 1e-5

model:
  model_arch: "Basic3DAE"
  loss_function: "MSELoss"
  #loss_params:
  #  example: 0.01

training:
  amp: True  # include autoMixedPrecision (default: False)
  start_epoch: 0
  epochs: 50
  warmup_epochs: 10
  log_interval:
  checkpoint_interval: